networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chhiris_vale
    expose:
      - '8000'
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./audio:/app/audio  

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy_chhiris_vale
    ports:
      - '0.0.0.0:8088:80'
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./audio:/app/audio
    depends_on:
      - app